### ISSUE TITLE
survey: gRPCのfpsに制限はあるのか？

### ISSUE THREAD

**Issue by karamaru-alpha** [CA22-game-creators/cookingbomb-server#16]
## 概要
毎秒10リクエストが限界って本当？

**Comment by karamaru-alpha** [comment]
@moritaoy 
毎秒の通信回数に制限があるような記述が調べても見つからなかったんだけど、なにか文献とかあったりする？👀

この[Grpcでカメラ映像をストリームで共有する](https://qiita.com/iwax10/items/8631534ea6b02cdf2024#%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%81%AE%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88%E4%BD%9C%E6%88%90)も10fps以上は出てる気がするんだけど.....

**Comment by moritaoy** [comment]
ごめん、説明が悪かったかも！
gRPCはUDPに対応してなくてTCPでしか通信できないみたい。
ここがボトルネックになって、リアルタイム通信の時には注意しないといけない！
見たいな記事を見かけたんだよね...ドキュメント見つけますm(__)m

**Comment by karamaru-alpha** [comment]
へーそうなんだありがとう！
僕UDPの存在も知らなかったから勉強になりましたmm

秒間リクエスト数は気をつけて設定しないとね👀

**Comment by karamaru-alpha** [comment]
まずは10req/secとかにして、それで監視とか負荷テストとかして様子見よっか！

https://github.com/CA22-game-creators/cookingbomb-server/issues/10　とかに委譲します

**Comment by moritaoy** [comment]
かしこまり！！
確かに組んで試すのが一番楽ね！
